# Configuração do Netlify para Perfect Wedding
# Este arquivo configura otimizações de desempenho para o site

[build]
  # Diretório que contém os arquivos estáticos a serem publicados
  publish = "brides/"
  
  # Comando de build a ser executado antes da publicação
  command = "npm run build:css"

# Configurações para todos os arquivos
[[headers]]
  for = "/*"
  [headers.values]
    # Habilitar compressão de texto
    Content-Encoding = "br, gzip"
    
    # Habilitar HSTS para segurança
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Prevenir clickjacking
    X-Frame-Options = "DENY"
    
    # Proteção XSS
    X-XSS-Protection = "1; mode=block"
    
    # Prevenir MIME type sniffing
    X-Content-Type-Options = "nosniff"

# Configurações específicas para arquivos CSS
[[headers]]
  for = "*.css"
  [headers.values]
    # Cache por 1 ano
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações específicas para arquivos JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    # Cache por 1 ano
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações específicas para imagens
[[headers]]
  for = "*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    # Cache por 1 ano
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações específicas para fontes
[[headers]]
  for = "*.{woff,woff2,ttf,otf,eot}"
  [headers.values]
    # Cache por 1 ano
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações específicas para HTML
[[headers]]
  for = "*.html"
  [headers.values]
    # Cache por 1 hora (para permitir atualizações mais frequentes)
    Cache-Control = "public, max-age=3600"

# Redirecionamentos
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# Configurações de compressão Brotli
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true 