name: Deploy to Netlify
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            node_modules/.cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Configure Netlify env vars
        run: |
          echo "Configurando variáveis de ambiente no Netlify..."
          netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
          
          # Variáveis públicas
          netlify env:set NEXT_PUBLIC_BASE_URL "${{ vars.NEXT_PUBLIC_BASE_URL }}"
          netlify env:set NEXT_PUBLIC_API_URL "${{ vars.NEXT_PUBLIC_API_URL }}"
          netlify env:set NEXT_PUBLIC_DEFAULT_LOCALE "${{ vars.NEXT_PUBLIC_DEFAULT_LOCALE }}"
          netlify env:set NEXT_TELEMETRY_DISABLED "${{ vars.NEXT_TELEMETRY_DISABLED }}"
          
          # Google Analytics
          netlify env:set GOOGLE_ANALYTICS_ID "${{ vars.GOOGLE_ANALYTICS_ID }}"
          netlify env:set GOOGLE_SITE_VERIFICATION "${{ vars.GOOGLE_SITE_VERIFICATION }}"
          
          # Contentful - variáveis não secretas
          netlify env:set CONTENTFUL_SPACE_ID "${{ vars.CONTENTFUL_SPACE_ID }}"
          netlify env:set CONTENTFUL_ENVIRONMENT_ID "${{ vars.CONTENTFUL_ENVIRONMENT_ID }}"
          netlify env:set CONTENTFUL_PREVIEW "${{ vars.CONTENTFUL_PREVIEW }}"
          
          # Contentful - variáveis secretas (com contexto production obrigatório)
          netlify env:set CONTENTFUL_ACCESS_TOKEN "${{ secrets.CONTENTFUL_ACCESS_TOKEN }}" --secret --context production
          netlify env:set CONTENTFUL_MANAGEMENT_TOKEN "${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}" --secret --context production
          netlify env:set CONTENTFUL_PREVIEW_ACCESS_TOKEN "${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}" --secret --context production
          netlify env:set CONTENTFUL_REVALIDATE_SECRET "${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}" --secret --context production
          
          echo "Variáveis de ambiente configuradas com sucesso no Netlify"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Create simple netlify.toml
        run: |
          cat > netlify.toml << EOF
          [build]
            command = "npm run build"
            publish = ".next"
          
          [[plugins]]
            package = "@netlify/plugin-nextjs"
          
          [build.environment]
            NODE_VERSION = "20"
            NPM_VERSION = "10"
            NEXT_TELEMETRY_DISABLED = "1"
            NODE_ENV = "production"
          
          [[headers]]
            for = "/*"
            [headers.values]
              X-Frame-Options = "DENY"
              X-XSS-Protection = "1; mode=block"
              X-Content-Type-Options = "nosniff"
              Referrer-Policy = "strict-origin-when-cross-origin"
          EOF
          echo "netlify.toml criado"

      - name: Deploy to Netlify
        run: |
          echo "Starting Netlify deployment..."
          netlify deploy --build --prod --message "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}